apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics

  labels:
    version: v1.9.5

spec:
  clusterIP: None

  ports:
  - name: https-main
    port: 8443
    targetPort: https-main
  - name: https-self
    port: 9443
    targetPort: https-self