apiVersion: batch/v1
kind: Job
metadata:
  name:  prometheus-operator-tls-create
  namespace: monitoring

  labels:
    component: tls-create-job
    name: prometheus-operator
    version: v0.38.1

spec:
  template:
    metadata:
      name:  prometheus-operator-tls-create
      labels:
        component: tls-create-job
        name: prometheus-operator
        version: v0.38.1

    spec:
      serviceAccountName: prometheus-operator-tls-create

      containers:
      - name: certgen
        image: jettech/kube-webhook-certgen:v1.2.0
        args:
        - create
        - --host=prometheus-operator,prometheus-operator.monitoring.svc
        - --namespace=monitoring
        - --secret-name=prometheus-operator-tls

      restartPolicy: OnFailure

      securityContext:
        runAsNonRoot: true
        runAsUser: 2000