apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# consider using operator-tls instead

resources:
- clusterrole.yaml
- clusterrolebinding.yaml
- deployment.yaml
- service.yaml
- serviceaccount.yaml

commonLabels:
  component: controller
  name: prometheus-operator

# namespace elided intentionally