apiVersion: v1
kind: Service
metadata:
  name: prometheus-operator
  namespace: monitoring

  labels:
    version: v0.38.1

spec:
  clusterIP: None # we let kube-rbac-proxy handle the proxying from inside the pod

  ports:
  - name: https
    port: 8443
    targetPort: https