apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-operator
  namespace: monitoring

  labels:
    version: v0.38.1

spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    port: https
    scheme: https
    tlsConfig:
      insecureSkipVerify: true

  selector:
    matchLabels: # must match up to commonLabels in kustomization.yaml
      component: controller
      name: prometheus-operator