apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- alertmanager
- blackbox-exporter
- control-plane
- grafana
- kube-prometheus
- kube-state-metrics
- node-exporter
- prometheus
- prometheus-adapter
- prometheus-operator
- setup
