apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  labels:
    app: node-exporter
  name: psp-node-exporter
spec:
  fsGroup:
    ranges:
    - max: 65535
      min: 0
    rule: RunAsAny
  hostIPC: false
  hostNetwork: true
  hostPID: true
  hostPorts:
  - max: 65535
    min: 0
  privileged: false
  readOnlyRootFilesystem: false
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    ranges:
    - max: 65535
      min: 0
    rule: RunAsAny
  volumes:
  - configMap
  - emptyDir
  - projected
  - secret
  - downwardAPI
  - persistentVolumeClaim
  - hostPath
