apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: prometheus
  name: prometheus
  namespace: monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: tenancy
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  selector:
    matchLabels:
      prometheus: k8s
