apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- alertmanager.yaml
- podmonitor.yaml
- prometheus.yaml
- prometheusrule.yaml
- servicemonitor.yaml
- thanosruler.yaml # lol