kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: grafana

subjects:
  - kind: ServiceAccount
    name: grafana
    namespace: monitoring

roleRef:
  kind: ClusterRole
  name: grafana
  apiGroup: rbac.authorization.k8s.io