apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: grafana

rules:
- apiGroups:      ['policy']
  resources:      ['podsecuritypolicies']
  verbs:          ['use']
  resourceNames:  [grafana]
