kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-alertmanager

rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - prometheus-alertmanager
