apiVersion: v1
kind: Service
metadata:
  name: etcd-k8s
  labels:
    app: etcd
    etcd: k8s
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/job: etcd
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: api
    port: 2379
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: etcd-k8s
  labels:
    app: etcd
    etcd: k8s
subsets:
- addresses:
  - ip: 172.17.4.51
    nodeName: 172.17.4.51
  ports:
  - name: api
    port: 2379
    protocol: TCP
