apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- prometheusRule.yaml
- serviceMonitorApiserver.yaml
- serviceMonitorCoreDNS.yaml
- serviceMonitorKubeControllerManager.yaml
- serviceMonitorKubeScheduler.yaml
- serviceMonitorKubelet.yaml
